name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: jbbriand2
          password: Clerc794613
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jbbriand2/app:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
