name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . -t simpleweb

    - name: Login to DockerHub
    - uses: actions/checkout@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build and push
    - uses: docker/build-push-action@v2
      with:
          context: actions/checkout@v2
          push: true
          tags: user/app:latest
    
